### PR TITLE
fix typo in readme, add require

### PR DESCRIPTION
**Pull request by jeffbski**
Fix the typo in readme, MyForm is declared but then DecoratedMyForm is used in app so it is confusing.

Also just for clarity add require to complete the example.

### CODE REVIEW

**Comment by mikaelbr** [comment]
Thank you very much!

**Comment by jeffbski** [comment]
You are welcome, I'm excited about this HOC, it's just what I was looking for.

**Comment by mikaelbr** [comment]
Great! It's trying to be just a minimal form-to-object library, and it works great for my use case at least. Feel free to continue to send prs or issues, but I'm trying to keep ir minimal. I can also add you as a collaborator if you are interested?

**Comment by jeffbski** [comment]
Will do. I agree with that approach. One reason for its appeal is that it is simple and just serves this small feature set. Yes I would be happy to be a collaborator. I'll post issues or PR's if I run into any important shortcomings. Thanks.

**Comment by mikaelbr** [comment]
Brilliant. Thanks alot. Added you now

**Pull request merged**
